version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - ./master/my.cnf:/etc/mysql/my.cnf
      - master-data:/var/lib/mysql
      - ./master/init-master.sql:/docker-entrypoint-initdb.d/init-master.sql
    networks:
      - mysql-net

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./slave/my.cnf:/etc/mysql/my.cnf
      - slave-data:/var/lib/mysql
      - ./slave/init-slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
    depends_on:
      - mysql-master
    networks:
      - mysql-net

networks:
  mysql-net:

volumes:
  master-data:
  slave-data:
