services:
  kafka-1:
    container_name: kafka-1
    image: bitnami/kafka:latest
    hostname: kafka-1
    ports:
      - "9092:9092"
      - "9093:9093"  # Controller 端口
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CLUSTER_ID=kafka-cluster
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LISTENERS=INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./data/data-1:/bitnami/kafka/data
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    ports:
      - '9001:9000'
    environment:
      - KAFKA_BROKERCONNECT=kafka-1:9092
      - JVM_OPTS=-Xmx128m
    depends_on:
      - kafka-1

    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
