// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type User struct {
	Id         int    `json:"id"`
	Username   string `json:"username"`
	Created_at string `json:"created_at"`
	Updated_at string `json:"updated_at"`
}

type UserLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}

type UserPageReq struct {
}

type UserPageResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    User   `json:"data"`
}

type UserRegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserRegisterResp struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
	Data    string `json:"data"`
}
